<?php echo $this->doctype() ?>
<html lang="ja">
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(array(
        'rel' => 'shortcut icon', 
        'href' => $this->baseUrl('/favicon.ico')
      ), 'PREPEND')
    ?>

    <?php 
    echo $this->jQuery()
        // jQuery UI
        ->setUiVersion('1.9.1')
# set jquery ui theme 
#        ->addStyleSheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css')
        // Twitter bootstrap
        ->addJavaScriptFile($this->baseUrl('/js/bootstrap.js'))
        ->addStylesheet($this->baseUrl('/css/bootstrap.css'))
    ?>
  </head>

  <body>
    <?php echo $this->layout()->content; ?>
  </body>
</html>
<?php // vim:set ts=2 sts=2 sw=2 expandtab fdm=marker: ?>
